<a href="https://colab.research.google.com/github/wli1992/The-Pandas-Workshop/blob/main/Activity06_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#
# required libraries
#
import pandas as pd
#

In [ ]:
#
# read in the abalone.csv data
#
abalone = pd.read_csv('..//Datasets//abalone.csv')
abalone.head()
#

,Sex,Length,Diameter,Height,Whole weight,.Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [ ]:
#
# create a MultiIndex from Sex and Rings
#
my_index = pd.MultiIndex.from_frame(abalone[['Sex', 'Rings']])
abalone.drop(columns = ['Sex', 'Rings'], inplace = True)
abalone.set_index(my_index, inplace = True)
abalone.head(10)
#

           Length  Diameter  Height  Whole weight  .Shucked weight  \
Sex Rings
M   15      0.455     0.365   0.095        0.5140           0.2245
    7       0.350     0.265   0.090        0.2255           0.0995
F   9       0.530     0.420   0.135        0.6770           0.2565
M   10      0.440     0.365   0.125        0.5160           0.2155
I   7       0.330     0.255   0.080        0.2050           0.0895
    8       0.425     0.300   0.095        0.3515           0.1410
F   20      0.530     0.415   0.150        0.7775           0.2370
    16      0.545     0.425   0.125        0.7680           0.2940
M   9       0.475     0.370   0.125        0.5095           0.2165
F   19      0.550     0.440   0.150        0.8945           0.3145

           Viscera weight  Shell weight
Sex Rings
M   15             0.1010         0.150
    7              0.0485         0.070
F   9              0.1415         0.210
M   10             0.1140         0.155
I   7              0.0395         0.055
    8              0.0775         0.120
F   20             0.1415         0.330
    16             0.1495         0.260
M   9              0.1125         0.165
F   19             0.1510         0.320

In [ ]:
#
# select male with more than 15 rings, and store the mean Length, Diameter, Height, and .Shucked weight in a Series
#
min_rings = 16
#
all_rings_M = set(abalone.loc['M'].index)
max_rings_M = max(abalone.loc['M'].index)
rings_M = [i for i in range(min_rings, max_rings_M + 1)
           if i in all_rings_M]
males = \
abalone.loc['M'].loc[rings_M][['Length',
                               'Diameter',
                               'Height',
                               '.Shucked weight']].mean(axis = 0)
#
# repeat for females
#
all_rings_F = set(abalone.loc['F'].index)
max_rings_F = max(abalone.loc['F'].index)
rings_F = [i for i in range(min_rings, max_rings_F + 1)
           if i in all_rings_F]
females = \
abalone.loc['F'].loc[rings_F][['Length',
                               'Diameter',
                               'Height',
                               '.Shucked weight']].mean(axis = 0)
#
# inspect the intermediate results
#
print(males)
print(females)

Length             0.602826
Diameter           0.478304
Height             0.175609
.Shucked weight    0.457943
dtype: float64
Length             0.602746
Diameter           0.479180
Height             0.173566
.Shucked weight    0.449443
dtype: float64

In [ ]:
#
# compare the results
#
print('for oysters with', min_rings, 'or more rings\n')
print('males weigh', round(males['.Shucked weight'], 3),
     'vs. females weigh', round(females['.Shucked weight'], 3))
print('males are', round(males['Length'], 3), 'long ',
     'vs. females are', round(females['Length'], 3), 'long')
print('males are', round(males['Diameter'], 3), 'in diameter ',
     'vs. females are', round(females['Diameter'], 3), 'in diameter')
print('males are', round(males['Height'], 3), 'in height ',
     'vs. females are', round(females['Height'], 3), 'in height')

for oysters with 16 or more rings

males weigh 0.458 vs. females weigh 0.449
males are 0.603 long  vs. females are 0.603 long
males are 0.478 in diameter  vs. females are 0.479 in diameter
males are 0.176 in height  vs. females are 0.174 in height